version: "3.8"

services:
  app_web: 
    container_name: alejandria_web
    build: ./client/library
    ports: 
      - 3000:3000
    volumes:
      - ".:/app"
      - "/app/node_modules"
    networks:
      - alejandria

  server:
    container_name: alejandria_back
    image: library-api:0.0.1-SNAPSHOT
    ports: 
      - 8080:8080
    env_file:
      - ./db/.env    
    networks:
      - alejandria

  db:
    container_name: alejandria_db
    image: postgres:14.1-alpine
    env_file:
      - ./db/.env
    ports:
      - 5430:5432
    volumes:
      - ./db/scripts/:/home/postgres/scripts
      - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - alejandria

volumes:
  pgdata: {}
networks:
  alejandria:
    driver: bridge


